### ISSUE TITLE
无法回放脚本执行过程，回放时出现语法错误，但是我检查代码没有发现缺少“）”

### ISSUE THREAD

**Issue by Kaleym** [alibaba/uirecorder#102]
录制成功后，npm run server开启webdriver server, 然后在录制目录npm install, run.bat.输出错误信息：
it('url: http://www.baidu.com', async function(){
SyntaxError: missing ) after argument list
 at createScript (vm.js:56:10)
 at Object.runInThisContext (vm.js:97:10)
 at Module._compile (module.js:542:28)
 at Object.Module._extensions..js (module.js:579:10)
 at Module.load (module.js:487:32)
 at tryModuleLoad (module.js:446:12)
 at Function.Module._load (module.js:438:3)
 at Module.require (module.js:497:17)
 at require (internal/module.js:20:19)

**Comment by yaniswang** [comment]
nodejs要安装v7.x或v8.x
