### ISSUE TITLE
录制的脚本回放报错

### ISSUE THREAD

**Issue by chyzhangxue** [alibaba/uirecorder#108]
报错信息如下：
D:\Tools\UI Recorder>mocha test.js

  test : chrome
    1) "before all" hook
    2) "after all" hook

  test : ie 11
    3) "before all" hook
    4) "after all" hook

  0 passing (2s)
  4 failing

  1) test : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

  2) test : chrome "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

  3) test : ie 11 "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

  4) test : ie 11 "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

**Comment by chyzhangxue** [comment]
uirecorder为最新版本，node.js也是最新版本。谷歌浏览器版本：58。ie版本：10

**Comment by yaniswang** [comment]
4444端口连接失败，说明你的webdriver server没有启动

**Comment by chyzhangxue** [comment]
好的，已解决，谢谢
