### ISSUE TITLE
2.5版安装卡在Installing spdx-license-ids

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#117]
最近试着装了一下最新的2.5版本。

执行npm install uirecorder mocha -g后挺顺利的，没有问题。

但是，用uirecorder init初始化项目的时候进行到一半却卡住不动了，命令行显示该位置为

[2/7] Installing spdx-license-ids@^1.0.2

根据观察，命令行长时间停在这里，而且期间也没有任何访问网络的行为，可以问一下是什么原因么？

**Comment by yaniswang** [comment]
建议用cnpm来安装:https://npm.taobao.org/

**Comment by stevobm** [comment]
好的，我用cnpm试一下。
希望后面还是能够支持npm（其实我的npm已经用了taobao源，应该不慢）。

**Comment by yaniswang** [comment]
npm官方还是容易出现各种被墙的问题

**Comment by yaniswang** [comment]
怎么样？用cnpm安装顺利吗？

**Comment by stevobm** [comment]
成功了，O(∩_∩)O谢谢！

**Comment by stevobm** [comment]
npm好像确实有些不太稳定，下载软件包有的时候会超时。。

**Comment by stevobm** [comment]
目前2.5版已经安装成功，可以进行录制了。
但是现在遇到了录制后的用例无法正常执行的情况，使用run.bat时出现以下报错：
```
D:\webtest\t.js:16    
let driver, testVars;
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at D:\webtest\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\webtest\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (D:\webtest\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (D:\webtest\node_modules\mocha\bin\_mocha:458:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "singletest" "t.js"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecord
er "t.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter
mochawesome-uirecorder "t.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder "t.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\webtest\npm-debug.log
```
好像是用到了ES6新特性的用例无法被正确识别导致的，这种情况应该如何处理呢？

**Comment by yaniswang** [comment]
你的nodejs是什么版本？必需是node v7.x以上版本

**Comment by stevobm** [comment]
哦，那应该是我nodejs版本太旧了，现在是5.7，我升级一下。

**Comment by stevobm** [comment]
换了nodejs7.9，运行依旧报错：
```
D:\web5>run.bat testfda.js

> uirecorderTest@1.0.0 singletest D:\web5
> mocha --reporter mochawesome-uirecorder "testfda.js"

module.js:472
    throw err;
    ^

Error: Cannot find module 'jpeg-js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\web5\node_modules\_resemblejs-node@1.0.0@resemblej
s-node\resemblejs.js:8:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\web5\testfda.js:7:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at D:\web5\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\web5\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:219
:14)
    at Mocha.run (D:\web5\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (D:\web5\node_modules\_mocha@3.1.2@mocha\bin\_mocha:45
8:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by yaniswang** [comment]
删除node_modules目录，然后试试重新执行`cnpm install`

**Comment by stevobm** [comment]
cnpm之前我已经全局安装了。全局npm目录删了，这个工程目录也是新建的，但uirecorder init还是一样报错。
安装环境说明：Windows7操作系统，未翻墙，nodejs为7.9版本。从开始升级到现在折腾已经快一周了，但始终没能完全正常运行。
后面有空我会把uirecorder2.5在全新环境再安装一遍并录制成视频，麻烦你再看一下是哪里的问题。

**Comment by yaniswang** [comment]
缺少依赖这个问题，最近在windows端经常出现，我怀疑是uirecorder init的问题

mac下面从来没出现过这个问题。

**Comment by yaniswang** [comment]
我重新升了一个版本，2.5.14，初始化的时候，改为使用淘宝的镜像。

之前老是出现依赖缺失，怀疑是被墙了，现在改成使用淘宝镜像，有可能会问题解决掉

**Comment by stevobm** [comment]
我目前的安装大概流程是这样的——

1. 全新环境下，首先装nodejs7.9，并指定淘宝npm镜像源，然后装cnpm。
2. 用cnpm install uirecorder -g --chromedriver_version=2.25(暂时不想升级浏览器)安装uirecorder。
3. 新建文件夹进入，执行uirecorder init，浏览器选chrome，其他默认。然后就卡在某个点（不记得），我就中止并重新执行uirecorder init，反复两次后，安装成功。此时uirecorder录制功能可用，但是录制完后，使用run.bat，就出现以上报错。

**Comment by yaniswang** [comment]
你试试最新的2.5.14，看看是不是不会卡住了。
之前版本的uirecorder init是使用的官方npm的源，在国内有可能会被墙掉。

**Comment by yaniswang** [comment]
结果怎么样？

**Comment by stevobm** [comment]
新版OK了。O(∩_∩)O~

**Comment by yaniswang** [comment]
好的，那这个issue关闭了
