### ISSUE TITLE
结束录制报错，没办法成功生成录制文件

### ISSUE THREAD

**Issue by zhoulinxiang** [alibaba/uirecorder#137]
chrome版本： 62.0.3192.0（正式版本）dev （64 位）
chromedriver版本： 2.31
nodejs版本：7.10.1
uirecorder版本：2.5.27
点击结束录制之后报错：
/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/uirecorder/lib/start.js:1412
            recorderBrowser.close(function(){
                           ^

TypeError: Cannot read property 'close' of undefined
    at onEnd (/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/uirecorder/lib/start.js:1412:28)
    at Server.<anonymous> (/Users/zlx/.nvm/versions/node/v7.10.1/lib/node_modules/uirecorder/lib/start.js:1615:29)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitCloseNT (net.js:1577:8)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by yaniswang** [comment]
每次必现吗？你是MAC系统？

**Comment by yaniswang** [comment]
我本地最新版本是：
![image](https://user-images.githubusercontent.com/970390/29809271-1a484ee2-8cce-11e7-9890-d0e8d141d2f5.png)

**Comment by zhoulinxiang** [comment]
是mac系统 每次必现 我换个chrome 版本试试吧

**Comment by zhoulinxiang** [comment]
换了60版本好了 谢啦
