### ISSUE TITLE
Async issues

### ISSUE THREAD

**Issue by vicpara** [alibaba/uirecorder#141]
Hi,
When trying to run `source run.sh` I get an exception around the usage of async.
The folder structure is exactly as `uirecorder init ` generates.

```
> uirecorderTest@1.0.0 singletest /Users/victor/work/test-2
> mocha --reporter mochawesome-uirecorder "testtwo.js"

/Users/victor/work/test-2/testtwo.js:24
    it('url: http://google.com', async function(){
                                     ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/victor/work/test-2/node_modules/_mocha@3.1.2@mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/victor/work/test-2/node_modules/_mocha@3.1.2@mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/victor/work/test-2/node_modules/_mocha@3.1.2@mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/victor/work/test-2/node_modules/_mocha@3.1.2@mocha/bin/_mocha:458:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "singletest" "testtwo.js"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "testtwo.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter mochawesome-uirecorder "testtwo.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder "testtwo.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/victor/work/test-2/npm-debug.log
```

**Comment by vicpara** [comment]
Solved this problem by using the latest version of NodeJS. I was using the LTS version.
