### ISSUE TITLE
Chrome init failed under mac os

### ISSUE THREAD

**Issue by Fmajor** [alibaba/uirecorder#147]
下文中的[the test path]是我运行命令的目录
```
$ uirecorder init
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.33

Official Site: http://uirecorder.com
------------------------------------------------------------------

? Dom path config, extend: id, name, class data-id,data-name,type,data-type,role,data-role,data-value
? Black list RegExp for attribute value
? Black list RegExp for class value
? Hide before expect
? Webdriver host or ip 127.0.0.1
? Webdriver port 4444
? Browsers list firefox

config.json file saved
package.json file created
README.md file created
screenshots directory created
commons directory created
uploadfiles directory created
.editorconfig file created
.gitignore file created
install.sh file created
run.bat file created
run.sh file created
hosts file created
.vscode/launch.json file created

Start install project dependencies...
--------------------------------------------

✔ Installed 7 packages
✔ Linked 181 latest versions
✔ Run 0 scripts
deprecate mochawesome-uirecorder@1.5.21 › node-uuid@^1.4.1 Use uuid module instead
Recently updated (since 2017-09-21): 2 packages (detail see file [the test path]/node_modules/.recently_updates.txt)
✔ All packages installed (203 packages installed from npm registry, used 4s, speed 441.93kB/s, json 188(1.87MB), tarball 0B)

Start install webdriver dependencies...
--------------------------------------------

> uirecorderTest@1.0.0 installdriver [the test path]
> selenium-standalone install --drivers.firefox.baseURL=http://npm.taobao.org/mirrors/geckodriver --baseURL=http://npm.taobao.org/mirrors/selenium --drivers.chrome.baseURL=http://npm.taobao.org/mirrors/chromedriver --drivers.ie.baseURL=http://npm.taobao.org/mirrors/selenium

----------

selenium-standalone installation starting

----------

---
selenium install:
from: http://npm.taobao.org/mirrors/selenium/3.5/selenium-server-standalone-3.5.3.jar
to: [the test path]/node_modules/_selenium-standalone@6.9.0@selenium-standalone/.selenium/selenium-server/3.5.3-server.jar
---
chrome install:
from: http://npm.taobao.org/mirrors/chromedriver/2.32/chromedriver_mac64.zip
to: [the test path]/node_modules/_selenium-standalone@6.9.0@selenium-standalone/.selenium/chromedriver/2.32-x64-chromedriver
---
firefox install:
from: http://npm.taobao.org/mirrors/geckodriver/v0.18.0/geckodriver-v0.18.0-macos.tar.gz
to: [the test path]/node_modules/_selenium-standalone@6.9.0@selenium-standalone/.selenium/geckodriver/0.18.0-x64-geckodriver
-----
selenium-standalone installation finished
-----

$ uirecorder start
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.33

Official Site: http://uirecorder.com
------------------------------------------------------------------

? Test spec file name: sample/test.spec.js
? Open checker browser? Yes
? Browser size (example: 1024 x 768): maximize

Recorder server listen on: 9765
Chrome init failed!
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }
```

OS X EI Capitan: 10.11.6
npm: 5.4.2
node: v8.5.0
chrome: Version 61.0.3163.100 (Official Build) (64-bit)

试着在不同的文件夹下init了好几次，每次都是同样的错误
================= more info about my environment====================
我又进行了另外两个测试：
1. 我怀疑是我的chrome配置问题，于是在另外的文件夹下
```
==================selenium.js===========================
var webdriver = require('selenium-webdriver');
var browser = new webdriver.Builder().usingServer().withCapabilities({'browserName': 'chrome' }).build();
browser.get('http://www.baidu.com');
=====================================================
$ node selenium.js
```
正常弹出chrome, 打开baidu页面

2. 首先用debug工具定位到出错的代码，然后把出错的代码单独抠出来运行

在uirecord init后的文件夹下新建
```======================test_chrome.js==================
var JWebDriver = require('jwebdriver');
var driver = new JWebDriver({
    'host': '127.0.0.1',
    'port': 4444
});
var capabilities = {  // 这些值是debug时候的真实值
    "hosts": "127.0.0.1 localhost\n",
    "chromeOptions": {
        "args": [
            "--enable-automation",
            "--disable-bundled-ppapi-flash"
        ],
        "prefs": {
            "plugins.plugins_disabled": [
                "Adobe Flash Player"
            ]
        }
    }
}
console.log('0')
d = driver.session(capabilities, function*(error, browser){
    if(error){
        console.log(__('chrome_init_failed').red);
        console.log(error); // 运行 uirecord start时在这里出错
        if(/unable to connect to renderer/.test(error)){
            console.log(__('localhost_hosts_tip').red);
        }
        chromedriver.stop();
        process.exit(1);
    }
    else{
        console.log('1')
        yield browser.config({
            asyncScriptTimeout: 10000
        });
        console.log('2')
        yield callback(this);
        console.log('3')
    }
}).catch(function(e){ console.log('4') });
console.log('1')
==========================================================
$ node chrome_test.js
0
1
4
```

**Comment by Fmajor** [comment]
After dig into the code, i finally find a solution
```
$ cd [workingDir]/node_modules/_selenium-standalone@6.9.0@selenium-standalone/bin
$ ./selenium-standalone start -- -port 9766

because your code in 

===========/usr/local/lib/node_modules/uirecorder/lib/start.js==================
.....
    var driver = new JWebDriver({
        'host': '127.0.0.1',
        'port': 9766
    });
.....
```
now the `uirecorder start` work normally

but in the Quick Start part, i did not found requirement of manually opening the selenium-standalone server
is it a bug that mac os users must open the selenium server manually?
