### ISSUE TITLE
更新到2.5.33之后无法录制

### ISSUE THREAD

**Issue by pcyan** [alibaba/uirecorder#151]
```
C:\test_uirecorder>uirecorder sample/test.spec.js
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.33

Official Site: http://uirecorder.com
------------------------------------------------------------------

? 测试脚本文件名: sample/test.spec.js
? 打开同步校验浏览器？ Yes
? 浏览器大小 (格式：1024 x 768): maximize

录制服务器监听在端口: 9765
Chrome打开失败！
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }
```

之前用`2.5.2x`的时候还是可以正常使用的，后来回放遇到alert有点问题，就尝试升级到最新版，升级之后就不能录制了。重装uirecorder和重启也不行
win10
node v8.4.0
npm 5.4.2

**Comment by yaniswang** [comment]
你电脑重启试试，从错误信息上来看，应该是webdriver没有启动成功

**Comment by pcyan** [comment]
重启之后也不行，为什么显示`录制服务器监听在端口: 9765`，后面提示错误确却是`127.0.0.1:9766`，端口不一样

**Comment by pcyan** [comment]
进入到`uirecorder`的目录，找到`npm\node_modules\uirecorder\node_modules\chromedriver`，按照`readme.md`重新安装`chromedriver`之后就可以使用录制了
