### ISSUE TITLE
Problem with mochawesome: TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by duckscofield** [alibaba/uirecorder#155]
2 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1021:11)
      at _exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

  2) sample/test.spec : chrome "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1021:11)
      at _exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! uirecorderTest@1.0.0 paralleltest: `mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the uirecorderTest@1.0.0 paralleltest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by duckscofield** [comment]
is the same with issue#154

**Comment by yaniswang** [comment]
127.0.0.1:4444

Please start webdriver server first.

**Comment by duckscofield** [comment]
OS : mac Sierra
node : v8.7.0

I has execute `npm run server`, then execute `uirecorder`, show the fail

```
Problem with mochawesome: TypeError: Cannot read property 'title' of undefined
    at copyScreenShots (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:315:40)
    at cleanSuite (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:244:3)
    at /Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:225:9
    at arrayEach (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:3345:13)
    at traverseSuites (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:224:9)
    at RunnerWrapped.<anonymous> (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:97:9)
    at emitOne (events.js:120:20)
    at RunnerWrapped.emit (events.js:210:7)
    at RunnerWrapped.emit (/Users/duck/Downloads/tmp/node_modules/_mocha-parallel-tests@1.2.4@mocha-parallel-tests/dist/lib/utils/runner-wrapped.js:57:20)
```
