### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by neptunelsir** [alibaba/uirecorder#156]
When I carried out “npm run server” in windows7,the page show the following error

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\xxx\node_modules\_selenium-standalone@6.9.0@s
elenium-standalone\bin\selenium-standalone:3:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 server: `selenium-standalone start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2017-10-18T01_35_34_529
Z-debug.log

**Comment by Stngle** [comment]
运行 npm install
再运行 npm run installdriver
建议使用 cnpm
