### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by duckscofield** [alibaba/uirecorder#161]
1. npm start server
2. source run.sh

run test but no report, has error:

55 passing (12s)

Problem with mochawesome: TypeError: Cannot read property 'title' of undefined
    at copyScreenShots (.../tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:315:40)
    at cleanSuite (.../tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:244:3)
    at .../tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:225:9
    at arrayEach (.../tmp/node_modules/_lodash@3.10.1@lodash/index.js:1289:13)
    at Function.<anonymous> (.../tmp/node_modules/_lodash@3.10.1@lodash/index.js:3345:13)
    at traverseSuites (.../tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:224:9)
    at RunnerWrapped.<anonymous> (.../tmp/node_modules/_mochawesome-uirecorder@1.5.21@mochawesome-uirecorder/lib/mochawesome.js:97:9)
    at emitOne (events.js:120:20)
    at RunnerWrapped.emit (events.js:210:7)
    at RunnerWrapped.emit (.../tmp/node_modules/_mocha-parallel-tests@1.2.4@mocha-parallel-tests/dist/lib/utils/runner-wrapped.js:57:20)

**Comment by yaniswang** [comment]
Try new version uirecorder.

package.json: 

`"mochawesome-uirecorder": "1.5.22",`

**Comment by duckscofield** [comment]
```
  53 passing (9s)

Problem with mochawesome: TypeError: test.fullTitle is not a function
    at cleanTest (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:374:21)
    at arrayMap (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:1406:25)
    at Function.map (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:6710:14)
    at cleanSuite (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:254:22)
    at /Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:235:9
    at arrayEach (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:3345:13)
    at traverseSuites (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:234:9)
    at RunnerWrapped.<anonymous> (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:107:9)
    at emitOne (events.js:120:20)
```

I trace codes (in mochawesome-uirecorder package) and console message , not all tests object has `test.fullTitle`.

The same. Could not generator reporter correctly.

**Comment by yaniswang** [comment]
Can you upload your test case?

**Comment by duckscofield** [comment]
```

const fs = require('fs');
const path = require('path');
const chai = require("chai");
const should = chai.should();
const JWebDriver = require('jwebdriver');
chai.use(JWebDriver.chaiSupportChainPromise);
const resemble = require('resemblejs-node');
resemble.outputSettings({
    errorType: 'flatDifferenceIntensity'
});

const rootPath = getRootPath();

module.exports = function(){

    let driver, testVars;

    before(function(){
        let self = this;
        driver = self.driver;
        testVars = self.testVars;
    });

    it('url: https://www.google.com', async function(){
        await driver.url(_(`https://www.google.com`));
    });

    it('waitBody: ', async function(){
        await driver.sleep(500).wait('body', 30000).html().then(function(code){
            isPageError(code).should.be.false;
        });
    });

    it('scrollElementTo: #sfdiv div.lst-c, 0, 0', async function(){
        await driver.sleep(300).wait('#sfdiv div.lst-c', 30000)
               .sleep(300).scrollElementTo(0, 0);
    });

    it('sendKeys: hi{ENTER}', async function(){
        await driver.sendKeys('hi{ENTER}');
    });

    it('waitBody: ', async function(){
        await driver.sleep(500).wait('body', 30000).html().then(function(code){
            isPageError(code).should.be.false;
        });
    });

    function _(str){
        if(typeof str === 'string'){
            return str.replace(/\{\{(.+?)\}\}/g, function(all, key){
                return testVars[key] || '';
            });
        }
        else{
            return str;
        }
    }

};

if(module.parent && /mocha\.js/.test(module.parent.id)){
    runThisSpec();
}

function runThisSpec(){
    // read config
    let webdriver = process.env['webdriver'] || '';
    let proxy = process.env['wdproxy'] || '';
    let config = require(rootPath + '/config.json');
    let webdriverConfig = Object.assign({},config.webdriver);
    let host = webdriverConfig.host;
    let port = webdriverConfig.port || 4444;
    let match = webdriver.match(/([^\:]+)(?:\:(\d+))?/);
    if(match){
        host = match[1] || host;
        port = match[2] || port;
    }
    let testVars = config.vars;
    let browsers = webdriverConfig.browsers;
    browsers = browsers.replace(/^\s+|\s+$/g, '');
    delete webdriverConfig.host;
    delete webdriverConfig.port;
    delete webdriverConfig.browsers;

    // read hosts
    let hostsPath = rootPath + '/hosts';
    let hosts = '';
    if(fs.existsSync(hostsPath)){
        hosts = fs.readFileSync(hostsPath).toString();
    }
    let specName = path.relative(rootPath, __filename).replace(/\\/g,'/').replace(/\.js$/,'');

    browsers.split(/\s*,\s*/).forEach(function(browserName){
        let caseName = specName + ' : ' + browserName;

        let browserInfo = browserName.split(' ');
        browserName = browserInfo[0];
        let browserVersion = browserInfo[1];

        describe(caseName, function(){

            this.timeout(600000);
            this.slow(1000);

            let driver;
            before(function(){
                let self = this;
                let driver = new JWebDriver({
                    'host': host,
                    'port': port
                });
                let sessionConfig = Object.assign({}, webdriverConfig, {
                    'browserName': browserName,
                    'version': browserVersion,
                    'ie.ensureCleanSession': true,
                    'chromeOptions': {
                        'args': ['--enable-automation']
                    }
                });
                if(proxy){
                    sessionConfig.proxy = {
                        'proxyType': 'manual',
                        'httpProxy': proxy,
                        'sslProxy': proxy
                    }
                }
                else if(hosts){
                    sessionConfig.hosts = hosts;
                }
                self.driver = driver.session(sessionConfig).maximize().config({
                    pageloadTimeout: 30000, // page onload timeout
                    scriptTimeout: 5000, // sync script timeout
                    asyncScriptTimeout: 10000 // async script timeout
                });
                self.testVars = testVars;
                let casePath = path.dirname(caseName);
                self.screenshotPath = rootPath + '/screenshots/' + casePath;
                self.diffbasePath = rootPath + '/diffbase/' + casePath;
                self.caseName = caseName.replace(/.*\//g, '').replace(/\s*[:\.\:\-\s]\s*/g, '_');
                mkdirs(self.screenshotPath);
                mkdirs(self.diffbasePath);
                self.stepId = 0;
                return self.driver;
            });

            module.exports();

            beforeEach(function(){
                let self = this;
                self.stepId ++;
                if(self.skipAll){
                    self.skip();
                }
            });

            afterEach(async function(){
                let self = this;
                let currentTest = self.currentTest;
                let title = currentTest.title;
                if(currentTest.state === 'failed' && /^(url|waitBody|switchWindow|switchFrame):/.test(title)){
                    self.skipAll = true;
                }
                if(!/^(closeWindow):/.test(title)){
                    let filepath = self.screenshotPath + '/' + self.caseName + '_' + self.stepId;
                    let driver = self.driver;
                    try{
                        // catch error when get alert msg
                        await driver.getScreenshot(filepath + '.png');
                        let url = await driver.url();
                        let html = await driver.source();
                        html = '<!--url: '+url+' -->\n' + html;
                        fs.writeFileSync(filepath + '.html', html);
                        let cookies = await driver.cookies();
                        fs.writeFileSync(filepath + '.cookie', JSON.stringify(cookies));
                    }
                    catch(e){}
                }
            });

            after(function(){
                return this.driver.close();
            });

        });
    });
}

function getRootPath(){
    let rootPath = path.resolve(__dirname);
    while(rootPath){
        if(fs.existsSync(rootPath + '/config.json')){
            break;
        }
        rootPath = rootPath.substring(0, rootPath.lastIndexOf(path.sep));
    }
    return rootPath;
}

function mkdirs(dirname){
    if(fs.existsSync(dirname)){
        return true;
    }else{
        if(mkdirs(path.dirname(dirname))){
            fs.mkdirSync(dirname);
            return true;
        }
    }
}

function callSpec(name){
    try{
        require(rootPath + '/' + name)();
    }
    catch(e){
        console.log(e)
        process.exit(1);
    }
}

function isPageError(code){
    return code == '' || / jscontent="errorCode" jstcache="\d+"|diagnoseConnectionAndRefresh|dnserror_unavailable_header|id="reportCertificateErrorRetry"|400 Bad Request|403 Forbidden|404 Not Found|500 Internal Server Error|502 Bad Gateway|503 Service Temporarily Unavailable|504 Gateway Time-out/i.test(code);
}

function catchError(error){

}

```

**Comment by Stngle** [comment]
try new version "mochawesome-uirecorder": "1.5.25"
