### ISSUE TITLE
`npm install uirecorder -g` has some error

### ISSUE THREAD

**Issue by duckscofield** [alibaba/uirecorder#164]
use windows 10, node v8.8.0
run `npm install uirecorder -g`, has some error

```
verbose lifecycle typechecker@2.0.8~preinstall: unsafe-perm in lifecycle true
verbose lifecycle typechecker@2.0.8~preinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\duck\AppData\Roaming\npm\node_modules\uirecorder\node_modules\extract-opts\node_modules\typechecker\node_modules\.bin;C:\Users\duck\AppData\Roaming\npm\node_modules\uirecorder\node_modules\extract-opts\node_modules\.bin;C:\Users\duck\AppData\Roaming\npm\node_modules\uirecorder\node_modules\.bin;C:\Users\duck\AppData\Roaming\npm\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\duck\AppData\Local\Microsoft\WindowsApps;C:\Users\duck\AppData\Roaming\npm
verbose lifecycle typechecker@2.0.8~preinstall: CWD: C:\Users\duck\AppData\Roaming\npm\node_modules\uirecorder\node_modules\extract-opts\node_modules\typechecker
silly lifecycle typechecker@2.0.8~preinstall: Args: [ '/d /s /c', 'node ./cyclic.js' ]
silly lifecycle typechecker@2.0.8~preinstall: Returned: code: 0  signal: null
verbose stack TypeError: Cannot read property 'pause' of undefined
verbose stack     at runCmd (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:212:12)
verbose stack     at dequeue (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:201:12)
verbose stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
verbose cwd C:\Users\duck\Desktop\uirecorderTest
verbose Windows_NT 10.0.14393
verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "uirecorder" "-g"
verbose node v8.8.0
verbose npm  v5.4.2
error Cannot read property 'pause' of undefined
verbose exit [ 1, true ]
```

**Comment by duckscofield** [comment]
after `npm install mocha -g'
then run the script again `npm install uirecorder -g`
has no error.

I don't know why

**Comment by duckscofield** [comment]
在新专案里开始进行 `recorder` 时,有出现一个小警告,不知需不需要理会它？

![20171026-1](https://user-images.githubusercontent.com/8048120/32032912-0f4b1826-ba3c-11e7-8107-d68c4fdbbbf7.png)
![20171026-2](https://user-images.githubusercontent.com/8048120/32032913-0f74ccc0-ba3c-11e7-86c3-0b4621ae011c.png)
![20171026-3](https://user-images.githubusercontent.com/8048120/32032914-0fc0aa8c-ba3c-11e7-8572-cc4b49aa34b4.png)

**Comment by yaniswang** [comment]
没看到任何严重错误，，试着录制下，应该没什么大问题。

**Comment by duckscofield** [comment]
接下来就是 #139 那个状况， Chrome 打开失败！弄了 2 天，不知还有什么方式可以解开

**Comment by yaniswang** [comment]
你看下chromedriver的二进制是否已经下载到你本地目录中？

**Comment by duckscofield** [comment]
在 C 槽下去搜寻得到下面资讯，看来是有的，但它自动装到 temp 下，不知是不是这样有影响？ 
![findchromedriver](https://user-images.githubusercontent.com/8048120/32042526-73853186-ba6a-11e7-93bc-a18abb1fbe61.png)


另个截图是在专案资料下去搜寻的结果
![findchromedriver-local](https://user-images.githubusercontent.com/8048120/32042532-772ddd7e-ba6a-11e7-81e7-8aeaa8b6ee21.png)

**Comment by duckscofield** [comment]
#157 已能录制
