### ISSUE TITLE
Problem with mochawesome: TypeError: test.fullTitle is not a function

### ISSUE THREAD

**Issue by duckscofield** [alibaba/uirecorder#167]
```
Problem with mochawesome: TypeError: test.fullTitle is not a function
    at cleanTest (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:374:21)
    at arrayMap (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:1406:25)
    at Function.map (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:6710:14)
    at cleanSuite (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:254:22)
    at /Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:235:9
    at arrayEach (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/duck/Downloads/tmp/node_modules/_lodash@3.10.1@lodash/index.js:3345:13)
    at traverseSuites (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:234:9)
    at RunnerWrapped.<anonymous> (/Users/duck/Downloads/tmp/node_modules/_mochawesome-uirecorder@1.5.22@mochawesome-uirecorder/lib/mochawesome.js:107:9)
    at emitOne (events.js:120:20)
 duck @MackBook Pro  📂 tmp $ ./node_modules/.bin/uirecorder --version
    __  ______   ____                           __         
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /    
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.34

Official Site: http://uirecorder.com
------------------------------------------------------------------

2.5.34

```

**Comment by Stngle** [comment]
新版 mochawesome-uirecorder 已做兼容
