### ISSUE TITLE
关于uirecorder在代理环境安装chromedriver失败的问题

### ISSUE THREAD

**Issue by stevobm** [alibaba/uirecorder#168]
在代理环境下全新安装uirecorder的时候，发现每次都会在"node install.js"这一步之后报错，而正常环境则没有这个问题，具体报错信息如下：
```
F:\WebAutoTest>cnpm i -g uirecorder
Downloading uirecorder to C:\Users\stevobm\AppData\Roaming\npm\node_modules\uir
ecorder_tmp
Copying C:\Users\stevobm\AppData\Roaming\npm\node_modules\uirecorder_tmp\_uirec
order@2.5.34@uirecorder to C:\Users\stevobm\AppData\Roaming\npm\node_modules\ui
recorder
Installing uirecorder's dependencies to C:\Users\stevobm\AppData\Roaming\npm\no
de_modules\uirecorder/node_modules
[1/16] co@4.6.0 installed at node_modules\_co@4.6.0@co
[2/16] colors@1.1.2 installed at node_modules\_colors@1.1.2@colors
[3/16] commander@2.9.0 installed at node_modules\_commander@2.9.0@commander
[4/16] chai@3.5.0 installed at node_modules\_chai@3.5.0@chai
[5/16] semver@5.3.0 installed at node_modules\_semver@5.3.0@semver
[6/16] os-locale@1.4.0 installed at node_modules\_os-locale@1.4.0@os-locale

WARN node unsupported "node@v8.1.3" is incompatible with latest-version@2.0.0 ›
package-json@2.4.0 › got@^5.0.0, expected node@>=0.10.0 <7
[7/16] fs-extra@1.0.0 installed at node_modules\_fs-extra@1.0.0@fs-extra
scripts.preinstall i18n@0.8.3 › messageformat@0.3.1 › watchr@2.4.13 › extract-op
ts@2.2.0 › typechecker@~2.0.1  "node ./cyclic.js"
[8/16] async@2.1.2 installed at node_modules\_async@2.1.2@async
[npminstall:get] retry GET http://registry.npm.taobao.org/eachr/download/eachr-2
.0.4.tgz after 100ms, retry left 4, error: ResponseError: read ECONNRESET (req "
error"), GET https://cdn.npm.taobao.org/eachr/-/eachr-2.0.4.tgz -1 (connected: t
rue, keepalive socket: true)
headers: {}
[9/16] websocket@1.0.22 installed at node_modules\_websocket@1.0.22@websocket
[10/16] latest-version@2.0.0 installed at node_modules\_latest-version@2.0.0@lat
est-version
[11/16] i18n@0.8.3 installed at node_modules\_i18n@0.8.3@i18n
[12/16] jwebdriver@2.2.4 installed at node_modules\_jwebdriver@2.2.4@jwebdriver
[13/16] inquirer@3.0.1 installed at node_modules\_inquirer@3.0.1@inquirer
[14/16] chromedriver@2.x.x installed at node_modules\_chromedriver@2.33.2@chrome
driver
[15/16] npminstall@3.1.1 installed at node_modules\_npminstall@3.1.1@npminstall
[16/16] resemblejs-node@1.0.0 installed at node_modules\_resemblejs-node@1.0.0@r
esemblejs-node
execute post install 2 scripts...
[1/2] scripts.install websocket@1.0.22 run "(node-gyp rebuild 2> builderror.log)
 || (exit 0)"

C:\Users\stevobm\AppData\Roaming\npm\node_modules\uirecorder\node_modules\_webs
ocket@1.0.22@websocket>node "C:\Users\stevobm\AppData\Roaming\npm\node_modules\
cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
[1/2] scripts.install websocket@1.0.22 finished in 3s
[2/2] scripts.install chromedriver@2.x.x run "node install.js"
Downloading https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/chromedriver/2.33/
chromedriver_win32.zip
Saving to C:\Users\stevobm\AppData\Local\Temp\chromedriver\chromedriver_win32.z
ip
ChromeDriver installation failed Error with http(s) request: Error: connect ETIM
EDOUT 116.62.99.12:443
Install fail! Error: post install error, please remove node_modules before retry
!
Run "C:\Windows\system32\cmd.exe /d /s /c node install.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c node install.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\stevobm\AppData\Roaming\npm\node_mod
ules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
npminstall version: 3.2.1
npminstall args: D:\Program Files\nodejs\node.exe C:\Users\stevobm\AppData\Roam
ing\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --proxy
=http://proxy.vosoft.com.cn:80 --userconfig=C:\Users\stevobm\.cnpmrc --disturl=h
ttps://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org -g
uirecorder
```
初步分析，可能是由于这个脚本没有使用设置中的代理进行下载导致的，因为无论用npm还是cnpm安装都会有这个问题(虽然两者下载chromedriver的地址不一样)。

**Comment by stevobm** [comment]
找到原因了，是由于chromedriver的包要用到https-proxy，我之前配置漏了。。
