### ISSUE TITLE
这个应该怎么解决/

### ISSUE THREAD

**Issue by everyday-up** [alibaba/uirecorder#176]
D:\UIrecorder  (uirecorderTest@1.0.0)
λ mocha  sample/test.spec.js --reporter mochawesome

  sample/test.spec : chrome
    1) "before all" hook
    2) "after all" hook

  0 passing (1s)
  2 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1024:11)
      at _exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

  2) sample/test.spec : chrome "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1024:11)
      at _exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

**Comment by landou1107** [comment]
建议重新 初始化

**Comment by yaniswang** [comment]
webdriver没开，执行：npm run server
