### ISSUE TITLE
正则匹配好像有点问题，加的\转义字符无法匹配

### ISSUE THREAD

**Issue by luoxi001713** [alibaba/uirecorder#194]
录制的，实际输入为/^\d{11}$/ ，生成的代码加了个\转义字符，为should.match(/^\\d{11}$/); 执行后匹配失败

去掉转义\后， should.match(/^\d{11}$/); 可以匹配

**Comment by yaniswang** [comment]
这个问题已经在2.5.36上修复了

**Comment by luoxi001713** [comment]
@yaniswang 非常感谢，更新了是OK的。

有办法将正则放到config.json文件 变量里么，是我的使用姿势不对么，
should.match(_(/{'{regexPhone}}/');

报错：
`
TypeError: re.exec is not a function
      at Assertion.assertMatch (node_modules/_chai@3.5.0@chai/lib/chai/core/assertions.js:1075:12)
      at Assertion.ctx.(anonymous function) (node_modules/_chai@3.5.0@chai/lib/chai/utils/addMethod.js:41:25)
      at Promise.<anonymous> (node_modules/_promiseclass@1.0.3@promiseclass/lib/promiseclass.js:177:26)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by yaniswang** [comment]
变量没办法存正则
