### ISSUE TITLE
录制完运行source run.sh sample/test.spec.js 报错

### ISSUE THREAD

**Issue by BestDingSheng** [alibaba/uirecorder#216]
``` bash
➜  uirecorder git:(master) ✗ source run.sh sample/test.spec.js

> uirecorderTest@1.0.0 singletest /Users/deson/Desktop/mposLkl/学习笔记/uirecorder
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

[mochawesome] Generating report files...



  sample/test.spec : chrome
    1) "before all" hook

  0 passing (34ms)
  1 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object._errnoException (util.js:1024:11)
      at _exceptionWithHostPort (util.js:1046:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)




[mochawesome] Report saved to reports/index.html
[mochawesome] Report saved to reports/index.xml


(node:1857) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1857) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1857) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deson/.npm/_logs/2018-01-16T13_37_45_604Z-debug.log


```

**Comment by yaniswang** [comment]
同意

**Comment by yaniswang** [comment]
错误信息中已经写清了原因：connect ECONNREFUSED 127.0.0.1:4444

是因为你的webdriver server没有启动，连接失败

**Comment by BestDingSheng** [comment]
@yaniswang  老铁 如何启动 webdriver server

**Comment by yaniswang** [comment]
http://uirecorder.com/

请仔细看官方的使用步骤，每一步都讲的很清楚了

**Comment by BestDingSheng** [comment]
@yaniswang   啊，大佬能告知下吗 第三部没看到运行命令啊 
![image](https://user-images.githubusercontent.com/13111768/35034460-3962d028-fba9-11e7-829f-2c345b8687c3.png)

**Comment by yaniswang** [comment]
![image](https://user-images.githubusercontent.com/970390/35034552-878d5ec6-fba9-11e7-8ebb-d76c4d2d4df3.png)

**Comment by BestDingSheng** [comment]
@yaniswang  哦哦 一直没往下面看  谢谢大佬
