### ISSUE TITLE
 运行报错：Cannot find module 'assertion-error'

### ISSUE THREAD

**Issue by junzhen6888** [alibaba/uirecorder#218]
Error: Cannot find module 'assertion-error'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\zhengxuexian\node_modules\_chai@3.5.0@chai\lib\chai.js:20:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\zhengxuexian\node_modules\_chai@3.5.0@chai\index.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\zhengxuexian\sample\test.spec.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

**Comment by Stngle** [comment]
依赖安装缺失模块，运行 npm install，再运行 npm run installdirver
