### ISSUE TITLE
录制完脚本后,运行会报错

### ISSUE THREAD

**Issue by zhangjianpinghik** [alibaba/uirecorder#219]
共录制3个步骤，其中校验通过: 3个，校验失败: 0个
录制脚本已保存: sample/test.spec.js

录制服务器已关闭
录制浏览器已关闭
校验浏览器已关闭

F:\uirecord_test>run.bat sample/test.spec.js

> uirecorderTest@1.0.0 singletest F:\uirecord_test
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

F:\uirecord_test\sample\test.spec.js:24
    it('url: http://www.baidu.com', async function(){
                                    ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\lib\moc
ha.js:219:14)
    at Mocha.run (F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:
487:10)
    at Object.<anonymous> (F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\bin\
_mocha:458:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "singletest" "sample/test.spec.js"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecord
er --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter
mochawesome-uirecorder --bail "sample/test.spec.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js
"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\uirecord_test\npm-debug.log

F:\uirecord_test>
F:\uirecord_test>
F:\uirecord_test>
F:\uirecord_test>
F:\uirecord_test>run.bat sample/test.spec.js

> uirecorderTest@1.0.0 singletest F:\uirecord_test
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

F:\uirecord_test\sample\test.spec.js:24
    it('url: http://www.baidu.com', async function(){
                                    ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\lib\moc
ha.js:219:14)
    at Mocha.run (F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:
487:10)
    at Object.<anonymous> (F:\uirecord_test\node_modules\_mocha@3.1.2@mocha\bin\
_mocha:458:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "singletest" "sample/test.spec.js"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecord
er --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter
mochawesome-uirecorder --bail "sample/test.spec.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js
"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\uirecord_test\npm-debug.log

**Comment by zhangjianpinghik** [comment]
@yaniswang   帮我看看我的这个问题 .麻烦了

**Comment by shaoronglei** [comment]
@zhangjianpinghik 你的Nodejs是什么版本的，升级到7以上试试看

**Comment by TestingNG** [comment]
我的Nodejs

**Comment by TestingNG** [comment]
![image](https://user-images.githubusercontent.com/26453547/37756038-dcc323f6-2de2-11e8-9f7e-ab71a48323a6.png)

**Comment by TestingNG** [comment]
我的NodeJS v6.11.3也报这个错

**Comment by Stngle** [comment]
升级 node版本7.x 以上，jwebdriver 更新至最新版本
