### ISSUE TITLE
 Error: the string "exec timeout" was thrown, throw an Error :)；自动运行case是可以正常运行的，但是日志会一直报这样的错误；怎么解决

### ISSUE THREAD

**Issue by deddddd** [alibaba/uirecorder#233]
ssociationProject/associationProject.test : chrome 滚动鼠标:
base.js:225
     Error: the string "exec timeout" was thrown, throw an Error :)
      at Runner.fail (D:\uirecorder\node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at D:\uirecorder\node_modules\_mocha@3.1.2@mocha\lib\runner.js:566:18
      at done (D:\uirecorder\node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at D:\uirecorder\node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Stngle** [comment]
能否提供更详细的日志？
