### ISSUE TITLE
Android：get apk mainifest failed with: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by zhangpeng23796** [alibaba/uirecorder#238]
当运行某个apk是会报错，apk下载地址:http://app.autohome.com.cn/app/ashx/rd/rd.ashx?id=333&rd=http%3a%2f%2fapp.autohome.com.cn%2fdownload%2fahprice.apk
，报错信息如下：
>> UIAutomatorWD http server ready
>> responseHandler.js:56:12 [master] pid:99804 Send Error Respone to Client: get apk mainifest failed with: TypeError: Cannot read property '1' of null

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/_koa@1.1.2@koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/_webdriver-server@1.1.4@webdriver-server/lib/server/responseHandler.js:59:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/_co@4.6.0@co/index.js:81:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by xiaoluohardup** [comment]
@zhangpeng23796  请问出现这个报错要怎么解决呢？
