### ISSUE TITLE
运行单个脚本,执行命令run.bat sample/test.spec.js，（报错）求助求助，谢谢

### ISSUE THREAD

**Issue by gqm19950828** [alibaba/uirecorder#244]
C:\Users\youtai>run.bat sample/test.spec.js

> uirecorderTest@1.0.0 singletest C:\Users\youtai
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

module.js:545
    throw err;
    ^

Error: Cannot find module 'json3'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\youtai\node_modules\_mocha@3.1.2@mocha\lib\u
tils.js:9:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecord
er --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2018-04-17T06_51_41_167Z-d
ebug.log

**Comment by yaniswang** [comment]
这个问题可能是依赖的组件安装缺失，再试下执行uirecorder init命令
