### ISSUE TITLE
TypeError: string.replace is not a function

### ISSUE THREAD

**Issue by wwllss** [alibaba/uirecorder#250]
使用uirecorder start --mobile命令后报错：

/usr/local/lib/node_modules/uirecorder/bin/uirecorder:23
    var nocolor = string.replace(/[\d+[mdc]|\[K)/gi, '');
                         ^

TypeError: string.replace is not a function
    at WriteStream.process.stdout.write (/usr/local/lib/node_modules/uirecorder/bin/uirecorder:23:26)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)

**Comment by mingmingmignhui** [comment]
使用uirecorder start也会报这个错误。 @yaniswang 这个要怎么解决？

**Comment by wwllss** [comment]
@mingmingmignhui 我是把报错地方的string.replace换成string.toString().replace好了。你可以试下。
