### ISSUE TITLE
使用uirecorder命令报错：srting.replace is not afunction

### ISSUE THREAD

**Issue by mingmingmignhui** [alibaba/uirecorder#251]
在windows上使用uirecorder命令时报错,报错如下：
Users\npm\node_modules\uirecorder\bin\uirecorder:23
    var nocolor = string.replace(/[\d+[mdc]|\[K)/gi, '');
                         ^

TypeError: string.replace is not a function
    at WriteStream.process.stdout.write (C:\Users\\npm\node_modules\uirecorder\bin\uirecorder:23:26)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20) 
@yaniswang 这个要如何解决

**Comment by lyn02** [comment]
我也遇到了同样的问题，请问你解决了吗

**Comment by Racheljia1989** [comment]
我也遇到了，请问解决没有？

**Comment by Racheljia1989** [comment]
I resolved this proble by change "var nocolor = string.replace(/(\[\d+[mdc]|\[K)/gi, '');" to "var nocolor = string.toString().replace(/(\[\d+[mdc]|\[K)/gi, '');". Which was just add a "toString()" in the line 23 command.
