### ISSUE TITLE
【求助】运行脚本时报错，之前可运行

### ISSUE THREAD

**Issue by w243137321** [alibaba/uirecorder#254]
. run.sh sample/test.spec.js 

> uirecorderTest@1.0.0 singletest /Users/chimengdan
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

ERROR: Could not get device name!
child_process.js:644
    throw err;
    ^

Error: Command failed: idevice_id -d 47887f34373536e8aec4f9cf3030990248721c51
ERROR: Could not get device name!

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at /Users/chimengdan/sample/test.spec.js:338:33
    at String.replace (<anonymous>)
    at getDeviceList (/Users/chimengdan/sample/test.spec.js:337:17)
    at runThisSpec (/Users/chimengdan/sample/test.spec.js:220:41)
    at Object.<anonymous> (/Users/chimengdan/sample/test.spec.js:207:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /Users/chimengdan/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/chimengdan/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/Users/chimengdan/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/Users/chimengdan/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by yaniswang** [comment]
你是不是没有安装idevice_id？
