### ISSUE TITLE
运行时提示 Error: Cannot find module 'chai'

### ISSUE THREAD

**Issue by ghostMozi** [alibaba/uirecorder#257]
C:\Users\Administrator\uirecorder>mocha sample/test*
module.js:549
    throw err;
    ^

Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Administrator\uirecorder\sample\test.spec.js
:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\mocha\lib\mocha.j
s:253:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\Administrator\AppData\Roaming\npm\node_modules\
mocha\lib\mocha.js:250:14)
    at Mocha.run (C:\Users\Administrator\AppData\Roaming\npm\node_modules\mocha\
lib\mocha.js:577:10)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\mocha\bin\_mocha:591:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by ghostMozi** [comment]
问题已解决
解决方法：
删除当前uirecorder目录下所有内容，重新安装
npm install uirecorder mocha -g
