### ISSUE TITLE
win7安装报错“The Windows SDK version 8.1 was not found.”

### ISSUE THREAD

**Issue by thxl2010** [alibaba/uirecorder#27]
win7安装报错：
```
cnpm install mocha -g

C:\Program Files\nodejs\node_modules\.uirecorder_npminstall\node_modules\.1.0.22@websocket>node "C:\Users\swj\AppData\Roaming\nvm\v4.6.1\node_modules\cnpm\node_modules\npminstall\node
-gyp-bin\\node-gyp.js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install th
e required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Program Files\nodej
s\node_modules\.uirecorder_npminstall\node_modules\.1.0.22@websocket\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install th
e required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Program Files\nodej
s\node_modules\.uirecorder_npminstall\node_modules\.1.0.22@websocket\build\validation.vcxproj]
deprecate uirecorder@1.4.0 › jwebdriver@1.0.13 › request@2.65.0 › tough-cookie@2.2.2 ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
√ All packages installed (131 packages installed from npm registry, use 56s, speed 516.34kB/s, json 261(1.8MB), tarball 26.52MB)
Recently updated (since 2016-10-24): 1 packages (detail see file node_modules/.recently_updates.txt)
  Today:
    → uirecorder@1.4.0 › inquirer@1.0.2 › lodash@4.16.5 (14:49:14)


```

**Comment by yaniswang** [comment]
你的nodejs是什么版本？

**Comment by thxl2010** [comment]
@yaniswang  v4.6.1

**Comment by yaniswang** [comment]
mocha按道理没有任何复杂的依赖，我从来没有安装错误过。
你试试用官方的安装
npm i mocha -g

**Comment by thxl2010** [comment]
哦，上边写错了，抱歉，应该是`cnpm install uirecorder -g`，下面的日志是对的。

**Comment by yaniswang** [comment]
npm install uirecorder@beta -g呢？

**Comment by thxl2010** [comment]
一样的问题
```
C:\Users\swj>npm install uirecorder@beta -g
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> websocket@1.0.22 install C:\Program Files\nodejs\node_modules\uirecorder\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
C:\Program Files\nodejs\node_modules\uirecorder\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\swj\AppData\Roaming\nvm\v4.6.1\node_mo
dules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 wa
s not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selectin
g "Retarget solution". [C:\Program Files\nodejs\node_modules\uirecorder\node_modules\websocket\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 wa
s not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selectin
g "Retarget solution". [C:\Program Files\nodejs\node_modules\uirecorder\node_modules\websocket\build\validation.vcxproj]

> typechecker@2.0.8 preinstall C:\Program Files\nodejs\node_modules\uirecorder\node_modules\i18n\node_modules\messageformat\node_modules\watchr\node_modules\ext
endr\node_modules\typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall C:\Program Files\nodejs\node_modules\uirecorder\node_modules\i18n\node_modules\messageformat\node_modules\watchr\node_modules\ext
ract-opts\node_modules\typechecker
> node ./cyclic.js

C:\Program Files\nodejs\uirecorder -> C:\Program Files\nodejs\node_modules\uirecorder\bin\uirecorder
uirecorder@2.0.0-b9 C:\Program Files\nodejs\node_modules\uirecorder
├── co@4.6.0
├── colors@1.1.2
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── os-locale@1.4.0 (lcid@1.0.0)
├── xml2map@1.0.2 (xml-writer@1.6.0, sax@0.4.2)
├── chai@3.5.0 (assertion-error@1.0.2, type-detect@1.0.0, deep-eql@0.1.3)
├── jwebdriver@2.0.0 (xtend@2.0.3, promiseclass@1.0.1, node-zip@1.1.1, request@2.65.0)
├── websocket@1.0.22 (yaeti@0.0.6, typedarray-to-buffer@3.0.5, debug@2.2.0, nan@2.0.9)
├── i18n@0.8.3 (sprintf-js@1.0.3, mustache@2.2.1, debug@2.2.0, math-interval-parser@1.1.0, make-plural@3.0.6, messageformat@0.3.1)
├── inquirer@1.0.2 (ansi-escapes@1.4.0, mute-stream@0.0.6, through@2.3.8, cli-width@2.1.0, strip-ansi@3.0.1, pinkie-promise@2.0.1, figures@1.7.0, run-async@2
.2.0, cli-cursor@1.0.2, string-width@1.0.2, chalk@1.1.3, rx@4.1.0, lodash@4.16.6)
├── async@2.1.2 (lodash@4.16.6)
└── faker@3.1.0

C:\Users\swj>
```

**Comment by yaniswang** [comment]
你这个应该算是已经安装好了吧

**Comment by thxl2010** [comment]
OK，多谢指导，已经可以运行chrome和ie，但是firefox报错。WebDriver 我只下了IEDriverServer和ChromeDriver，firefox没有配置，是这个原因吗？文档里没看到啊……

**Comment by yaniswang** [comment]
firefox要看你的webdriver是用的哪个版本？

**Comment by thxl2010** [comment]
@yaniswang firefox要用哪个webdriver？我下了这个**geckodriver-v0.11.1-win64**，还是报错
```
"before all" hook failed

Error: the string "Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: VISTA\nBuild info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:16 -0700'\nSystem info: host: 'swj-PC', ip: '10.0.0.200', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'\nDriver info: driver.version: FirefoxDriver" was thrown, throw an Error :)

```

```
15:28:38.967 INFO - Executing: [new session: Capabilities [{ie.ensureCleanSession=true, hosts=, browserName=firefox, platform=ANY}]])
15:28:38.969 INFO - Creating a new session for Capabilities [{ie.ensureCleanSession=true, hosts=, browserName=firefox, platform=ANY}]
15:28:38.970 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:16 -0700'
System info: host: 'swj-PC', ip: '10.0.0.200', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:183)
        at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:119)
        at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:95)
        at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:131)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:59)
        at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:36)
        at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:111)
        at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:189)
        at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:222)
        at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:184)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:150)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:16 -0700'
System info: host: 'swj-PC', ip: '10.0.0.200', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:96)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:64)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:209)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:86)
        ... 9 more
Caused by: org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: VISTA
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:16 -0700'
System info: host: 'swj-PC', ip: '10.0.0.200', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: FirefoxDriver
        at org.openqa.selenium.firefox.internal.Executable.<init>(Executable.java:75)
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:60)
        at org.openqa.selenium.firefox.FirefoxBinary.<init>(FirefoxBinary.java:56)
        at org.openqa.selenium.firefox.FirefoxDriver.getBinary(FirefoxDriver.java:234)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:135)
        ... 14 more
15:28:38.972 WARN - Exception: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: VISTA
Build info: version: '3.0.0', revision: '350cf60', time: '2016-10-13 10:48:16 -0700'
System info: host: 'swj-PC', ip: '10.0.0.200', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: FirefoxDriver
```

**Comment by thxl2010** [comment]
firefox没有安装到默认路径的原因吗？

**Comment by yaniswang** [comment]
是的，firefox要安装到默认路径下

**Comment by yaniswang** [comment]
搞定了吗？

**Comment by thxl2010** [comment]
OK,搞定了。firefox是重新安装到默认路径下的，非默认路径不知道怎么设置
