### ISSUE TITLE
uirecorder start无法启动浏览器，停留在?浏览器大小 (格式：1024 x 768): maximize这个位置

### ISSUE THREAD

**Issue by totoro1520** [alibaba/uirecorder#278]
uirecorder start 后
停留在? 浏览器大小 (格式：1024 x 768): maximize 这个位置没有反应

D:\>cd 05

D:\05>uirecorder start
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.5.42

Official Site: http://uirecorder.com
------------------------------------------------------------------

? 测试脚本文件名: sample/test.spec.js
? 打开同步校验浏览器？ Yes
? 浏览器大小 (格式：1024 x 768): maximize

**Comment by mulunfeng** [comment]
同问，没有任务报错信息，日志里也是console一样的内容!!!!

**Comment by totoro1520** [comment]
已经解决，安装安装node.js 8.x版本解决

**Comment by mulunfeng** [comment]
我装的是node 10.8.0的版本，也是同样的错误，难道要降版本？？ @totoro1520

**Comment by Stngle** [comment]
node 10.x 不兼容，node 8.x 版本可以

**Comment by 17716645596** [comment]
selenium-standalone install 安装报错！！！


Error: Could not download https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.5.jar: Error: connect ETIMEDOUT 172.217.161.144:443
    at Request.<anonymous> (D:\Nodejs\NND\node-v8.16.0-win-x64\node_modules\selenium-standalone\lib\install.js:386:12)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\Nodejs\NND\node-v8.16.0-win-x64\node_modules\selenium-standalone\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

C:\Users\Administrator>a

**Comment by Stngle** [comment]
提供具体操作步骤，报错效果图？
