### ISSUE TITLE
windows Android模拟器启动问题？

### ISSUE THREAD

**Issue by llxiao** [alibaba/uirecorder#28]
windows使用Android模拟器可以使用genymotion模拟器吗？
还是必须使用Android sdk来启动。

**Comment by llxiao** [comment]
uirecorder mobile启动报错
手机打开失败，请检查macaca是否配置正确？ { [Error: socket hang up] code: 'ECONNRESET' }

macaca终端出错
 InternalServerError: Internal Server Error
     at Object.module.exports.throw (C:\Users\lxiao\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\node_modules\koa\lib\context.js:91:23)
     at Object.module.exports (C:\Users\lxiao\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:57:17)
     at throw (native)
     at onRejected (C:\Users\lxiao\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:81:24)
     at process._tickCallback (node.js:369:9)

**Comment by yaniswang** [comment]
都可以，不过genymotion模拟器需要配一下sdk的地址。
