### ISSUE TITLE
uirecorder mobile启动报错

### ISSUE THREAD

**Issue by llxiao** [alibaba/uirecorder#29]
uirecorder mobile启动报错
手机打开失败，请检查macaca是否配置正确？ Internal Server Error

macaca终端出错
 InternalServerError: Internal Server Error
     at Object.module.exports.throw (C:\Users\lxiao\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\node_modules\koa\lib\context.js:91:23)
     at Object.module.exports (C:\Users\lxiao\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:57:17)
     at throw (native)
     at onRejected (C:\Users\lxiao\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:81:24)
     at process._tickCallback (node.js:369:9)

**Comment by yaniswang** [comment]
看下macaca那边的日志报错，是不是没有连接手机或模拟器？

**Comment by llxiao** [comment]
D:\project\uirecorder>macaca doctor

  macaca-doctor version: 1.0.23


  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v4.4.4

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_65`
  ANDROID_HOME is set to `D:\android\android-sdk-windows`
  Platforms is set to `D:\android\android-sdk-windows\platforms\android-23`
  Android tools is set to `D:\android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\android\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `C:\jvm\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.39
  electron: 1.1.4
  ios: 1.0.40


也没看到什么异常信息啊，就是
`D:\project\uirecorder>macaca server --port 4444 --verbose
>> request.js:24:12 [master] pid:10636 get remote update info failed.
>> index.js:17:12 [master] pid:6120 webdriver server start with config:
 { port: '4444',
  verbose: true,
  always: true,
  ip: '192.168.1.25',
  host: 'lxiao-PC',
  loaded_time: '2016-11-01 15:44:45' }
>> middlewares.js:17:10 [master] pid:6120 base middlewares attached
>> router.js:129:10 [master] pid:6120 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:6120 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","udid":"192.168.68.101:555
5","app":"D:\\project\\uirecorder\\aircare.apk"}}
>> session.js:47:10 [master] pid:6120 Creating session, sessionId: 422eaf9b-c564-4cae-8fd9-1a9dcecbe284.
>> helper.js:193:12 [master] pid:6120 Using local app form D:\project\uirecorder\aircare.apk
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
>> socket server ready
>> socket client ready
>> responseHandler.js:54:12 [master] pid:6120 Send Error Respone to Client: Wait For Condition timeout 60000
  InternalServerError: Internal Server Error
      at Object.module.exports.throw (C:\Users\lxiao\AppData\Roaming\npm\node_modules\.macaca-cli_npminstall\node_modules\.1.1.2@koa\lib\context.js:91:23)
      at Object.module.exports (C:\Users\lxiao\AppData\Roaming\npm\node_modules\.macaca-cli_npminstall\node_modules\.1.0.67@webdriver-server\lib\server\responseHandler.js:57:17)
      at throw (native)
      at onRejected (C:\Users\lxiao\AppData\Roaming\npm\node_modules\.macaca-cli_npminstall\node_modules\.4.6.0@co\index.js:81:24)
      at process._tickCallback (node.js:369:9)`

**Comment by yaniswang** [comment]
InternalServerError: Internal Server Error
这就是异常啊

**Comment by llxiao** [comment]
未找到错误原因，各种尝试为解决问题
