### ISSUE TITLE
录制好后，运行测试时报错：SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by henix** [alibaba/uirecorder#294]
运行命令：. ./run.sh sample/test.spec.js

```
> @ singletest /home/henix/uirecorder-test
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

/home/henix/uirecorder-test/sample/test.spec.js:178
                    self.driver = driver.session(sessionConfig){ $sizeCode }.config({
                                                               ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /home/henix/uirecorder-test/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/henix/uirecorder-test/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/henix/uirecorder-test/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/henix/uirecorder-test/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ singletest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/henix/.npm/_logs/2018-10-22T07_06_32_436Z-debug.log
```

看了下生成的 test.spec.js 的这部分：

```js
                try {
                    self.driver = driver.session(sessionConfig){ $sizeCode }.config({
                        pageloadTimeout: 30000, // page onload timeout
                        scriptTimeout: 5000, // sync script timeout
                        asyncScriptTimeout: 10000 // async script timeout
                    });
                } catch (e) {
                    console.log(e);
                }
```

的确是不符合 js 语法...对应源代码：
https://github.com/alibaba/uirecorder/blob/19e0fb76fac4f14f9e22917abada213cfdcd0dcf/template/jwebdriver.js#L109

node 版本 v10.12.0

**Comment by liushengxian** [comment]
cooooool

**Comment by Stngle** [comment]
最新版本已经解决
