### ISSUE TITLE
Error: Cannot find module 'yargs'

### ISSUE THREAD

**Issue by NishantMadkikar** [alibaba/uirecorder#308]
RootsInnovations-MacBook:~ roots$ source run.sh
> uirecorderTest@1.0.0 paralleltest /Users/roots
> mocha-parallel-tests "!(node_modules)/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5 --bail

module.js:549    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/roots/node_modules/_mocha-parallel-tests@1.2.4@mocha-parallel-tests/dist/bin/mocha-parallel-tests:10:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 paralleltest: `mocha-parallel-tests "!(node_modules)/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5 --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 paralleltest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/roots/.npm/_logs/2018-12-31T10_04_13_187Z-debug.log

**Comment by Stngle** [comment]
看报错应该是执行cmd的路径错了，在 uirecorder init 执行的目录下执行 source run.sh 试试。
