### ISSUE TITLE
录制好的PC网页，执行测试时候提示Platform must in (android, chrome, electron, ios, puppeteer)

### ISSUE THREAD

**Issue by stephenwang1011** [alibaba/uirecorder#364]
`>> session.js:47:16 [master] pid:20506 Platform must in (android, chrome, electron, ios, puppeteer)

  Error: >> session.js:47:16 [master] pid:20506 Platform must in (android, chrome, electron, ios, puppeteer)
      at Logger.error (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/xlogger/lib/xlogger.js:169:9)
      at detectDevice (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:47:16)
      at Object.createDevice (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:13:18)
      at createDevice.next (<anonymous>)
      at onFulfilled (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
      at /Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
      at new Promise (<anonymous>)
      at Object.co (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
      at Object.toPromise (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
      at next (/Users/young/.npm-global/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)

(node:20506) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

`

**Comment by wdjwxh** [comment]
应该是chromedriver的版本不对
