### ISSUE TITLE
对录制脚本进行回放，浏览器窗口是出来了，单脚本直接报错

### ISSUE THREAD

**Issue by zws5320** [alibaba/uirecorder#380]
sample/预发/FBI2.0/test-FBI2数据集-预 : chrome "before all" hook:
     Error: the string "unknown command: Cannot call non W3C standard command while in W3C mode\nBuild info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:42:28.403Z'\nSystem info: host: '4CV82313SZ', ip: '30.5.130.160', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_211'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@3.1.2@mocha\lib\runner.js:233:11)
      at Runner.failHook (node_modules\_mocha@3.1.2@mocha\lib\runner.js:273:8)
      at node_modules\_mocha@3.1.2@mocha\lib\runner.js:326:16
      at done (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:293:5)
      at Promise.<anonymous> (node_modules\_mocha@3.1.2@mocha\lib\runnable.js:354:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Stngle** [comment]
WebDriver 服务是 npm run server 启动的？

**Comment by Stngle** [comment]
参考文档：https://www.yuque.com/artist/uirecorder/uozk2g
