### ISSUE TITLE
edge can't be called

### ISSUE THREAD

**Issue by cs10606** [alibaba/uirecorder#383]
> uirecorderTest@1.0.0 singletest C:\Users\paul\uirecorder_test
> mocha --reporter macaca-reporter --reporter-options reportJSONFilename=index --bail "sample\test.spec.js"

  sample/test.spec : edge
    1) "before all" hook

  0 passing (20s)
  1 failing

  1) sample/test.spec : edge
       "before all" hook:
     Error: the string "Timed out waiting for driver server to start.\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'DESKTOP-JT7SRO3', ip: '10.0.1.98', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@5.2.0@mocha\lib\runner.js:235:11)
      at Runner.failHook (node_modules\_mocha@5.2.0@mocha\lib\runner.js:284:8)
      at C:\Users\paul\uirecorder_test\node_modules\_mocha@5.2.0@mocha\lib\runner.js:334:16
      at done (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:319:5)
      at Promise.<anonymous> (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:383:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by cs10606** [comment]
the file uirecorder_test\node_modules\_selenium-standalone@6.16.0@selenium-standalone\lib\default-config.js can set the version
