### ISSUE TITLE
ie11 replay error

### ISSUE THREAD

**Issue by cs10606** [alibaba/uirecorder#406]
1) test/test : ie 11
       "before all" hook:
     Error: the string "Invalid timeout type specified: ms\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'DESKTOP-96SL52F', ip: '169.254.252.70', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_151'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules\_mocha@5.2.0@mocha\lib\runner.js:235:11)
      at Runner.failHook (node_modules\_mocha@5.2.0@mocha\lib\runner.js:284:8)
      at D:\uirecorder\node_modules\_mocha@5.2.0@mocha\lib\runner.js:334:16
      at done (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:319:5)
      at Promise.<anonymous> (node_modules\_mocha@5.2.0@mocha\lib\runnable.js:383:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Stngle** [comment]
建议采用 F2etest WebDriver 云：

https://www.yuque.com/artist/uirecorder/uozk2g
https://www.yuque.com/artist/f2etest/webdriver-cloud-usage
