### ISSUE TITLE
source run.sh  报错

### ISSUE THREAD

**Issue by PiterYang** [alibaba/uirecorder#432]
设备 MacOS 10.14.5
chrome版本： 79.0.3945.88

Unhandled asynchronous exception: TypeError: tty.getWindowSize is not a function
    at Object.<anonymous> (/Users/yangtao/Desktop/project/uirecorder/node_modules/mocha/lib/reporters/base.js:128:11)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/yangtao/Desktop/project/uirecorder/node_modules/mocha/lib/reporters/index.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorder@3.1.8 paralleltest: `macaca-mocha-parallel-tests "!(node_modules)/**/*.spec.js" --reporter macaca-reporter --reporter-options reportJSONFilename=index,processAlwaysExitWithZero=true --max-parallel 5 --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uirecorder@3.1.8 paralleltest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Stngle** [comment]
试试使用 npm run singletest 运行测试脚本
