### ISSUE TITLE
chrome 80.0 version 回放case 失败

### ISSUE THREAD

**Issue by smellwithsun** [alibaba/uirecorder#449]
1) 
       sample/test.spec : ie 11
         "before all" hook:
     Error: the string "Unable to create new service: InternetExplorerDriverService\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'wuminghuideMacBook-pro.local', ip: 'fe80:0:0:0:10bf:38b8:23b7:8fc0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_211'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@5.2.0@mocha/lib/runner.js:235:11)
      at Runner.failHook (node_modules/_mocha@5.2.0@mocha/lib/runner.js:284:8)
      at /Users/neo/tools/uirecorder_test/node_modules/_mocha@5.2.0@mocha/lib/runner.js:334:16
      at done (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:319:5)
      at Promise.<anonymous> (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:383:11)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  2) 
       sample/test.spec : ie 11
         "after all" hook:
     Error: the string "Unable to create new service: InternetExplorerDriverService\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'wuminghuideMacBook-pro.local', ip: 'fe80:0:0:0:10bf:38b8:23b7:8fc0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_211'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@5.2.0@mocha/lib/runner.js:235:11)
      at Runner.failHook (node_modules/_mocha@5.2.0@mocha/lib/runner.js:284:8)
      at /Users/neo/tools/uirecorder_test/node_modules/_mocha@5.2.0@mocha/lib/runner.js:334:16
      at done (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:319:5)
      at Promise.<anonymous> (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:383:11)
      at <anonymous>

**Comment by Stngle** [comment]
OS 版本
NodeJS 版本
UIRecorder 版本
