### ISSUE TITLE
脚本打开远端浏览器失败

### ISSUE THREAD

**Issue by hulizong** [alibaba/uirecorder#454]
sample/test.spec : chrome
      1) "before all" hook
      2) "after all" hook

  0 passing (3s)
  2 failing

  1)
       sample/test.spec : chrome
         "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:58596
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

  2)
       sample/test.spec : chrome
         "after all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:58596
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by Stngle** [comment]
1. 检查网络是否连通
2. 检查 WebDriver 服务端是否有日志
