### ISSUE TITLE
run test case fail: unknown command: Cannot call non W3C standard command while in W3C mode

### ISSUE THREAD

**Issue by 276512204** [alibaba/uirecorder#483]
npm run singletest sample/test.spec.js 

> uirecorderTest@1.0.0 singletest /Users/zh***ng/shopee/projects/uitest
> mocha --reporter macaca-reporter --reporter-options reportJSONFilename=index,processAlwaysExitWithZero=true --bail "sample/test.spec.js"

  sample/test.spec : chrome
    1) "before all" hook

  0 passing (1s)
  1 failing

  1) sample/test.spec : chrome
       "before all" hook:
     Error: the string "unknown command: Cannot call non W3C standard command while in W3C mode\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'Zh***ngdeMacBook-Pro.local', ip: 'fe80:0:0:0:c3f:c1db:cc3d:cbd9%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.3', java.version: '1.8.0_181'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@5.2.0@mocha/lib/runner.js:235:11)
      at Runner.failHook (node_modules/_mocha@5.2.0@mocha/lib/runner.js:284:8)
      at /Users/zh***ng/shopee/projects/uitest/node_modules/_mocha@5.2.0@mocha/lib/runner.js:334:16
      at done (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:319:5)
      at Promise.<anonymous> (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:383:11)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

>> html reporter generated: /Users/zh***ng/shopee/projects/uitest/reports/index.html
>> json reporter generated: /Users/zh***ng/shopee/projects/uitest/reports/index.json
>> reporter config generated: /Users/zh***ng/shopee/projects/uitest/reports/config.json
    2) "after all" hook
>> html reporter generated: /Users/zh***ng/shopee/projects/uitest/reports/index.html
>> json reporter generated: /Users/zh***ng/shopee/projects/uitest/reports/index.json
>> reporter config generated: /Users/zh***ng/shopee/projects/uitest/reports/config.json

>> html reporter generated: /Users/zh***ng/shopee/projects/uitest/reports/index.html
>> json reporter generated: /Users/zh***ng/shopee/projects/uitest/reports/index.json
>> reporter config generated: /Users/zh***ng/shopee/projects/uitest/reports/config.json

 node --version
v12.18.3

chrome version:  84.0.4147.125

**Comment by chriscuba23** [comment]
do you have a conf file somewhere? If so find the w3c there and change the value to false
