### ISSUE TITLE
android录制报错

### ISSUE THREAD

**Issue by cjydayang** [alibaba/uirecorder#49]
uirecorder的错误信息：
手机打开失败，请检查macaca是否配置正确？ Internal Server Error

macaca server的log：

>> responseHandler.js:54:12 [master] pid:11206 Send Error Respone to Client: get apk mainifest failed with: TypeError: Cannot read property '1' of null

  InternalServerError: Internal Server Error
      at Object.throw (/opt/node-v6.9.1-linux-x64/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.1.2@koa/lib/context.js:91:23)
      at Object.module.exports (/opt/node-v6.9.1-linux-x64/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.0.68@webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/opt/node-v6.9.1-linux-x64/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by yaniswang** [comment]
你的macaca配置好了吗？

**Comment by cjydayang** [comment]
@yaniswang 谢谢回复

~$ macaca doctor
macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /opt/node-v6.9.1-linux-x64/bin/node
  node version: v6.9.1

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/opt/jdk`
  ANDROID_HOME is set to `/opt/android_develop/android_sdk`
  Platforms is set to `/opt/android_develop/android_sdk/platforms/android-24`
  Android tools is set to `/opt/android_develop/android_sdk/tools/android`
  ADB tool is set to `/opt/android_develop/android_sdk/platform-tools/adb`

  Installed driver list:

(node:12270) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
  android: 1.1.3

请问这样是配置好了吗？

**Comment by yaniswang** [comment]
macaca的问题，我没办法提供技术支持，反馈给macaca开源社区吧
