### ISSUE TITLE
各位大佬帮忙看一下，安卓打开失败服务端报错forward tcp:9001 tcp:9001执行失败，手动执行可以成功

### ISSUE THREAD

**Issue by zhaofeng8963** [alibaba/uirecorder#491]
服务端报错：
C:\Users\ZhaoFeng>macaca server --port 4444 --verbose
(node:4176) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4176) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:4176) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
>> request.js:11:12 [master] pid:4176 get remote update info failed.
(node:14680) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14680) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
>> index.js:15:12 [master] pid:14680 webdriver server start with config:
 {
  port: 4444,
  verbose: true,
  always: true,
  ip: '10.6.1.17',
  host: 'DESKTOP-JREJR11',
  loaded_time: '2020-11-19 21:03:38'
}
>> middlewares.js:17:10 [master] pid:14680 base middlewares attached
>> router.js:132:10 [master] pid:14680 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:14680 Recieve HTTP Request from Client[2020-11-19 21:15:28]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","app":"D:\\Project\\apk\\oltest.apk","udid":"46HDU19417003356"}}
>> session.js:58:10 [master] pid:14680 Creating session, sessionId: 1fccd841-772e-489b-ab4d-9f77539ae7d1.
>> helper.js:207:14 [master] pid:14680 Using local app form D:\Project\apk\oltest.apk
>> checking permissionPatterns: []
(node:14680) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:14680) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
>> responseHandler.js:56:12 [master] pid:14680 Send Error Respone to Client: Error: Command failed: D:\Program Files\Android\AndroidSdk\platform-tools\adb.exe -s 46HDU19417003356 forward tcp:9001 tcp:9001
'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

>> responseHandler.js:62:14 [master] pid:14680 Error: Command failed: D:\Program Files\Android\AndroidSdk\platform-tools\adb.exe -s 46HDU19417003356 forward tcp:9001 tcp:9001
'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

  Error: Command failed: D:\Program Files\Android\AndroidSdk\platform-tools\adb.exe -s 46HDU19417003356 forward tcp:9001 tcp:9001
  'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
  ���������ļ���

      at ChildProcess.exithandler (child_process.js:308:12)
      at ChildProcess.emit (events.js:315:20)
      at maybeClose (internal/child_process.js:1048:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

(node:14680) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

UIrecorder录制脚本启动报错
D:\project_android>uirecorder --mobile sample/test.spec.js
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v3.5.3

Official Site: http://uirecorder.com
------------------------------------------------------------------

? 测试脚本文件名: sample/test.spec.js
? App路径 (扩展名: apk, app, zip): D:\Project\apk\oltest.apk

录制服务器监听在端口: 53017

DevTools listening on ws://127.0.0.1:53027/devtools/browser/f1bda826-62fe-402f-a3e1-bad811797ce6
手机打开失败，请检查macaca是否配置正确？ Internal Server Error
Chrome打开失败！
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

环境检查macaca doctor
![1605791993(1)](https://user-images.githubusercontent.com/74699502/99671463-07975880-2aad-11eb-9785-e0b78921bcab.jpg)

**Comment by zhaofeng8963** [comment]
D:\Program Files\Android\AndroidSdk\platforms\android-25
D:\Program Files\Android\AndroidSdk\build-tools\25.0.2
D:\Program Files\Android\AndroidSdk\platform-tools--也是25的
对应版本都是25，实在找不到哪里错误，找其他类型问题卸载重装一样存在此问题

**Comment by Renwq** [comment]
和我的问题一样...

**Comment by Renwq** [comment]
> 和我的问题一样...
把SDK 路径中的空格去掉，重新配置一下环境变量就可以了
