### ISSUE TITLE
linux 回放失败报错： Error: the string "unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by chensheng0619** [alibaba/uirecorder#497]
日志：
[test@zj130 uirecorder-MHD]$ source run.sh sample/test.spec.js

> uirecorderTest@1.0.0 singletest
> mocha --reporter macaca-reporter --reporter-options reportJSONFilename=index,processAlwaysExitWithZero=true --bail "sample/test.spec.js"

(node:115374) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:115374) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
  sample/test.spec : chrome
    1) "before all" hook

  0 passing (134ms)
  1 failing

  1) sample/test.spec : chrome
       "before all" hook:
     Error: the string "unknown error: cannot find Chrome binary\n  (Driver info: chromedriver=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}),platform=Linux 3.10.0-1062.4.1.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 5 milliseconds\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'zj130', ip: '10.108.160.139', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.4.1.el7.x86_64', java.version: '1.8.0_232'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@5.2.0@mocha/lib/runner.js:235:11)
      at Runner.failHook (node_modules/_mocha@5.2.0@mocha/lib/runner.js:284:8)
      at /disk2/course/jenkins2018/workspace/uirecorder-MHD/node_modules/_mocha@5.2.0@mocha/lib/runner.js:334:16
      at done (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:319:5)
      at Promise.<anonymous> (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:383:11)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)

>> html reporter generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/index.html
>> json reporter generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/index.json
>> reporter config generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/config.json
    2) "after all" hook
>> html reporter generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/index.html
>> json reporter generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/index.json
>> reporter config generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/config.json

>> html reporter generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/index.html
>> json reporter generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/index.json
>> reporter config generated: /disk2/course/jenkins2018/workspace/uirecorder-MHD/reports/config.json

**Comment by amiralam0** [comment]
any fix?
