### ISSUE TITLE
录制正常，但是使用回放时会启动三个chrome浏览器（每个显示data；），已使用npm run server起服务

### ISSUE THREAD

**Issue by zsjayy** [alibaba/uirecorder#503]
uirecorder verison:3.5.3
nodejs versiob：v14.17.0
mocha version:8.4.0

1.启动npm run server --正常
2.回放用例 npm run singletest sample/test.spec.js--提示错误如下：
sample/test.spec : chrome
    1) "before all" hook

  0 passing (6s)
  1 failing

  1) sample/test.spec : chrome
       "before all" hook:
     Error: the string "Unable to create session from {\n  \"desiredCapabilities\": {\n    \"browserName\": \"chrome\",\n    \"chromeOptions\": {\n      \"w3c\": false\n    },\n    \"ie.ensureCleanSession\": true,\n    \"platform\": \"ANY\",\n    \"group\": \"default\"\n  },\n  \"capabilities\": {\n    \"firstMatch\": [\n      {\n        \"browserName\": \"chrome\",\n        \"goog:chromeOptions\": {\n          \"w3c\": false\n        }\n      },\n      {\n      }\n    ]\n  }\n}\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'JaydeMacBook-Air.local', ip: 'fe80:0:0:0:1067:9a51:ee7c:e7b3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.2', java.version: '16.0.1'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
      at Runner.fail (node_modules/_mocha@5.2.0@mocha/lib/runner.js:235:11)
      at Runner.failHook (node_modules/_mocha@5.2.0@mocha/lib/runner.js:284:8)
      at /Users/jay/Downloads/test/node_modules/_mocha@5.2.0@mocha/lib/runner.js:334:16
      at done (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:319:5)
      at Promise.<anonymous> (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:383:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

>> html reporter generated: /Users/jay/Downloads/test/reports/index.html
>> json reporter generated: /Users/jay/Downloads/test/reports/index.json
>> reporter config generated: /Users/jay/Downloads/test/reports/config.json
    2) "after all" hook
>> html reporter generated: /Users/jay/Downloads/test/reports/index.html
>> json reporter generated: /Users/jay/Downloads/test/reports/index.json
>> reporter config generated: /Users/jay/Downloads/test/reports/config.json

>> html reporter generated: /Users/jay/Downloads/test/reports/index.html
>> json reporter generated: /Users/jay/Downloads/test/reports/index.json
>> reporter config generated: /Users/jay/Downloads/test/reports/config.json

**Comment by junzuchen** [comment]
> uirecorder verison:3.5.3
> nodejs versiob：v14.17.0
> mocha version:8.4.0
> 
> 1.启动npm run server --正常
> 2.回放用例 npm run singletest sample/test.spec.js--提示错误如下：
> sample/test.spec : chrome
> 1) "before all" hook
> 
> 0 passing (6s)
> 1 failing
> 
> 1. sample/test.spec : chrome
>    "before all" hook:
>    Error: the string "Unable to create session from {\n  "desiredCapabilities": {\n    "browserName": "chrome",\n    "chromeOptions": {\n      "w3c": false\n    },\n    "ie.ensureCleanSession": true,\n    "platform": "ANY",\n    "group": "default"\n  },\n  "capabilities": {\n    "firstMatch": [\n      {\n        "browserName": "chrome",\n        "goog:chromeOptions": {\n          "w3c": false\n        }\n      },\n      {\n      }\n    ]\n  }\n}\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\nSystem info: host: 'JaydeMacBook-Air.local', ip: 'fe80:0:0:0:1067:9a51:ee7c:e7b3%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.2', java.version: '16.0.1'\nDriver info: driver.version: unknown" was thrown, throw an Error :)
>    at Runner.fail (node_modules/_mocha@5.2.0@mocha/lib/runner.js:235:11)
>    at Runner.failHook (node_modules/_mocha@5.2.0@mocha/lib/runner.js:284:8)
>    at /Users/jay/Downloads/test/node_modules/_mocha@5.2.0@mocha/lib/runner.js:334:16
>    at done (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:319:5)
>    at Promise. (node_modules/_mocha@5.2.0@mocha/lib/runnable.js:383:11)
>    at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> > > html reporter generated: /Users/jay/Downloads/test/reports/index.html
> > > json reporter generated: /Users/jay/Downloads/test/reports/index.json
> > > reporter config generated: /Users/jay/Downloads/test/reports/config.json
> > > 2) "after all" hook
> > > html reporter generated: /Users/jay/Downloads/test/reports/index.html
> > > json reporter generated: /Users/jay/Downloads/test/reports/index.json
> > > reporter config generated: /Users/jay/Downloads/test/reports/config.json
> 
> > > html reporter generated: /Users/jay/Downloads/test/reports/index.html
> > > json reporter generated: /Users/jay/Downloads/test/reports/index.json
> > > reporter config generated: /Users/jay/Downloads/test/reports/config.json

-----问题解决了么，遇到同样问题

**Comment by linlinyang** [comment]
同问

**Comment by zsjayy** [comment]
> 同问

检查自己的java版本是否过高，如果是，删除，安装java8
