### ISSUE TITLE
UI recorder 启动报错。

### ISSUE THREAD

**Issue by blue534** [alibaba/uirecorder#53]
@yaniswang 您好，请教个问题，我在使用UIrecorder时，启动报如下错误，请问该如何处理。
nodejs版本 7.2.1
C:\Users\...\AppData\Roaming\npm\node_modules\uirecorder\node_modules\promisecla
ss\lib\promiseclass.js:57
                let deferred = ChainPromise.defer();
                                            ^

TypeError: ChainPromise.defer is not a function
    at PromiseClass.wrapFunction [as session] (C:\Users\yhy\AppData\Roaming\npm\
node_modules\uirecorder\node_modules\promiseclass\lib\promiseclass.js:57:45)
    at newChromeBrowser (C:\Users\yhy\AppData\Roaming\npm\node_modules\uirecorde
r\lib\start.js:1180:12)
    at onReady (C:\Users\...\AppData\Roaming\npm\node_modules\uirecorder\lib\sta
rt.js:799:17)
    at Server.<anonymous> (C:\Users\yhy\AppData\Roaming\npm\node_modules\uirecor
der\lib\start.js:1088:9)
    at Server.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1288:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by yaniswang** [comment]
你安装 v6.x版本的Nodejs
