### ISSUE TITLE
录制成功后执行run.sh失败

### ISSUE THREAD

**Issue by mijiawei** [alibaba/uirecorder#67]
```
runtime:

> uirecorderTest@1.0.0 paralleltest /Users/micky
> mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5

Doing something
Doing something
/Users/micky/node_modules/appium/node_modules/openssl-wrapper/test/index.spec.js:2
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at files.forEach.file (/Users/micky/node_modules/mocha-parallel-tests/dist/bin-helper.js:97:9)
    at Array.forEach (native)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "paralleltest"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! uirecorderTest@1.0.0 paralleltest: `mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uirecorderTest@1.0.0 paralleltest script 'mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha-parallel-tests "*/**/*.spec.js" --reporter mochawesome-uirecorder --max-parallel 5
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/micky/npm-debug.log

```

**Comment by yaniswang** [comment]
我们的自动化方案是基于macaca实现的，看你的出错信息是appium里的

**Comment by mijiawei** [comment]
这里我执行单个脚本source run.sh sample/test.spec.js就不会报错
执行source rn.sh就会指到这里node_modules/appium/node_modules/openssl-wrapper/test/index.spec.js

**Comment by yaniswang** [comment]
怎么可能啊，我们的整体方案里和appium没任何关系啊，也没有对appium有依赖
