### ISSUE TITLE
真机录制的时候提示改错误： TypeError: Cannot read property 'sessionId' of undefined 

### ISSUE THREAD

**Issue by bensonday** [alibaba/uirecorder#86]
/usr/local/lib/node_modules/uirecorder/node_modules/_jwebdriver@2.1.1@jwebdriver/lib/browser.js:222
                    self.sessionId = ret.sessionId;
                                        ^

TypeError: Cannot read property 'sessionId' of undefined
    at PromiseClass.<anonymous> (/usr/local/lib/node_modules/uirecorder/node_modules/_jwebdriver@2.1.1@jwebdriver/lib/browser.js:222:41)
    at done (/usr/local/lib/node_modules/uirecorder/node_modules/_promiseclass@1.0.3@promiseclass/lib/promiseclass.js:65:51)
    at PromiseClass.<anonymous> (/usr/local/lib/node_modules/uirecorder/node_modules/_jwebdriver@2.1.1@jwebdriver/lib/jwebdriver.js:227:36)
    at done (/usr/local/lib/node_modules/uirecorder/node_modules/_promiseclass@1.0.3@promiseclass/lib/promiseclass.js:65:51)
    at Request._callback (/usr/local/lib/node_modules/uirecorder/node_modules/_jwebdriver@2.1.1@jwebdriver/lib/jwebdriver.js:139:13)
    at Request.self.callback (/usr/local/lib/node_modules/uirecorder/node_modules/_request@2.79.0@request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/uirecorder/node_modules/_request@2.79.0@request/request.js:1081:10)
    at emitOne (events.js:96:13)

真机录制的时候提示改错误： TypeError: Cannot read property 'sessionId' of undefined 
按照步骤一步一步下来的时候macaca app-inspector 都可以正常运行，不知该如何解...

**Comment by yaniswang** [comment]
你在录制过程中，是哪个操作碰到这个问题？

真机会碰到证书问题吧？

**Comment by bensonday** [comment]
还没有开始录制。
执行了
macaca server --port 4444
uirecorder --mobile
然后填写了包地址之后，就提示上面的错误了。

证书问题应该是不存在的。
我将samplecode里面的测试用例稍微改了一下也可以真机跑起来
app-inspector 检查元素也是可以真机运行的。
就是到了录制的时候出了问题。
求解。

**Comment by yaniswang** [comment]
请加我们的钉钉群，线上细聊。

**Comment by bensonday** [comment]
我下载了钉钉却找不到那个群。我也很绝望啊。

**Comment by yaniswang** [comment]
端口号必需是4444，不支持别的端口，你换成4445，肯定就挂 了。
