### ISSUE TITLE
【求问】录制回放报错

### ISSUE THREAD

**Issue by Nilmiao** [alibaba/uirecorder#91]
**录制回放报错：**
- 执行命令：run.bat D:/sample/test.spec.js

- 命令行log：                                                                
```                     
> uirecorderTest@1.0.0 singletest D:\                                                                                               
> mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"                                                                                                               
D:\sample\test.spec.js:23                                                                                                           
    it('sendKeys: 222', async function(){                                                                                   
                                ^^^^^                                                                                               
SyntaxError: missing ) after argument list                                                                                          
    at Object.exports.runInThisContext (vm.js:76:16)                                                                                
    at Module._compile (module.js:542:28)                                                                                           
    at Object.Module._extensions..js (module.js:579:10)                                                                             
    at Module.load (module.js:487:32)                                                                                               
    at tryModuleLoad (module.js:446:12)                                                                                             
    at Function.Module._load (module.js:438:3)                                                                                      
    at Module.require (module.js:497:17)                                                                                            
    at require (internal/module.js:20:19)                                                                                           
    at D:\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:222:27                                                                       
    at Array.forEach (native)                                                                                                       
    at Mocha.loadFiles (D:\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:219:14)                                                     
    at Mocha.run (D:\node_modules\_mocha@3.1.2@mocha\lib\mocha.js:487:10)                                                           
    at Object.<anonymous> (D:\node_modules\_mocha@3.1.2@mocha\bin\_mocha:458:18)                                                    
    at Module._compile (module.js:570:32)                                                                                           
    at Object.Module._extensions..js (module.js:579:10)                                                                             
    at Module.load (module.js:487:32)                                                                                               
    at tryModuleLoad (module.js:446:12)                                                                                             
    at Function.Module._load (module.js:438:3)                                                                                      
    at Module.runMain (module.js:604:10)                                                                                            
    at run (bootstrap_node.js:394:7)                                                                                                
    at startup (bootstrap_node.js:149:9)                                                                                            
    at bootstrap_node.js:509:3                                                                                                      
npm ERR! code ELIFECYCLE                                                                                                            
npm ERR! errno 1                                                                                                                    
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"`                        
npm ERR! Exit status 1                                                                                                              
npm ERR!                                                                                                                            
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"'.   
npm ERR! Make sure you have the latest version of node.js and npm installed.                                                        
npm ERR! If you do, this is most likely a problem with the uirecorderTest package,                                                  
npm ERR! not with npm itself.                                                                                                       
npm ERR! Tell the author that this fails on your system:                                                                            
npm ERR!     mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"                                                       
npm ERR! You can get information on how to open an issue for this project with:                                                     
npm ERR!     npm bugs uirecorderTest                                                                                                
npm ERR! Or if that isn't available, you can get their info via:                                                                    
npm ERR!     npm owner ls uirecorderTest                                                                                            
npm ERR! There is likely additional logging output above.                                                                                                                                          
npm ERR! A complete log of this run can be found in:                                                                                
npm ERR!     C:\nodejs\node-cache\_logs\2017-05-11T10_25_16_468Z-debug.log    
 ```                                                    
**详细log:**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\nodejs\\node-global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'singletest',
1 verbose cli   'D:/sample/test.spec.js' ]
2 info using npm@4.5.0
3 info using node@v6.10.0
4 verbose run-script [ 'presingletest', 'singletest', 'postsingletest' ]
5 info lifecycle uirecorderTest@1.0.0~presingletest: uirecorderTest@1.0.0
6 silly lifecycle uirecorderTest@1.0.0~presingletest: no script for presingletest, continuing
7 info lifecycle uirecorderTest@1.0.0~singletest: uirecorderTest@1.0.0
8 verbose lifecycle uirecorderTest@1.0.0~singletest: unsafe-perm in lifecycle true
9 verbose lifecycle uirecorderTest@1.0.0~singletest: PATH:xxxxxx
10 verbose lifecycle uirecorderTest@1.0.0~singletest: CWD: D:\
11 silly lifecycle uirecorderTest@1.0.0~singletest: Args: [ '/d /s /c',
11 silly lifecycle   'mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"' ]
12 silly lifecycle uirecorderTest@1.0.0~singletest: Returned: code: 1  signal: null
13 info lifecycle uirecorderTest@1.0.0~singletest: Failed to exec singletest script
14 verbose stack Error: uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\nodejs\node-global\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\nodejs\node-global\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid uirecorderTest@1.0.0
16 verbose cwd D:\
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\nodejs\\node-global\\node_modules\\npm\\bin\\npm-cli.js" "run" "singletest" "D:/sample/test.spec.js"
19 verbose node v6.10.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 1
23 error uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"`
23 error Exit status 1
24 error Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the uirecorderTest package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     mocha --reporter mochawesome-uirecorder "D:/sample/test.spec.js"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs uirecorderTest
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls uirecorderTest
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by yaniswang** [comment]
node版本必需是node v7.x

**Comment by litingjun2015** [comment]
您好， 我在pc回放录制脚本报错，node版本是 v7.10.1，请帮忙看下：

```
C:\bizapp3\sturdy\BizAppV3\tests\pc (master) (uirecorderTest@1.0.0)
$ run.bat sample/test.spec.js

> uirecorderTest@1.0.0 singletest C:\bizapp3\sturdy\BizAppV3\tests\pc
> mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"

[mochawesome] Generating report files...



  sample/test.spec : chrome
    1) "before all" hook

  0 passing (1s)
  1 failing

  1) sample/test.spec : chrome "before all" hook:
     Error: connect ECONNREFUSED 127.0.0.1:4444
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)




[mochawesome] Report saved to reports\index.html
[mochawesome] Report saved to reports\index.xml


(node:3252) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3252) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3252) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "singletest" "sample/test.spec.js"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uirecorderTest@1.0.0 singletest: `mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uirecorderTest@1.0.0 singletest script 'mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uirecorderTest package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --reporter mochawesome-uirecorder --bail "sample/test.spec.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uirecorderTest
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uirecorderTest
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-11-01T02_26_14_521Z-debug.log

```


[2017-11-01T02_26_14_521Z-debug.log](https://github.com/alibaba/uirecorder/files/1432940/2017-11-01T02_26_14_521Z-debug.log)

**Comment by yaniswang** [comment]
`npm run server` 这条命令没有执行

**Comment by litingjun2015** [comment]
@yaniswang 原来如此，谢谢！
