### ISSUE TITLE
回放脚本报错

### ISSUE THREAD

**Issue by chyzhangxue** [alibaba/uirecorder#95]
我之前搭建的uirecorder1.0版可以正常录制和回放，后来我升级uirecorder到最新的V2.5.2，后台提示我crome浏览器版本太低，我又升级谷歌到58.0.3029.96，之后又把cromedriver也升级了，node.js也升级到V7.10.0，但还是报错。
下面是错误日志：
0 passing (19ms)
  2 failing

  1) pcLogin : crome "before all" hook:
     TypeError: ChainPromise.defer is not a function
      at PromiseClass.wrapFunction [as session] (node_modules\jwebdriver\node_mo
dules\promiseclass\lib\promiseclass.js:51:45)
      at Context.<anonymous> (pcLogin:119:40)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules\mocha-generators\node_modules\co\index.js:65:
19)
      at node_modules\mocha-generators\node_modules\co\index.js:54:5
      at co (node_modules\mocha-generators\node_modules\co\index.js:50:10)
      at Context.args.(anonymous function) (node_modules\mocha-generators\index.
js:50:6)

  2) pcLogin : ie11 "before all" hook:
     TypeError: ChainPromise.defer is not a function
      at PromiseClass.wrapFunction [as session] (node_modules\jwebdriver\node_mo
dules\promiseclass\lib\promiseclass.js:51:45)
      at Context.<anonymous> (pcLogin:119:40)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules\mocha-generators\node_modules\co\index.js:65:
19)
      at node_modules\mocha-generators\node_modules\co\index.js:54:5
      at co (node_modules\mocha-generators\node_modules\co\index.js:50:10)
      at Context.args.(anonymous function) (node_modules\mocha-generators\index.
js:50:6)

**Comment by yaniswang** [comment]
1. 删除package.json
2. uirecorder init
3. cnpm install

**Comment by chyzhangxue** [comment]
按照你的操作后，上面的那个错误没有了，但又有别的问题了，麻烦能再帮忙看下吗？谢谢！
错误日志如下：
0 passing (380ms)
  2 failing

  1) pcLogin : crome "before all" hook:
     Error: done() invoked with non-Error: The best matching driver provider org
.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance fo
r Capabilities [{ie.ensureCleanSession=true, hosts=, browserName=crome, platform
=ANY}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'yzy-PC', ip: '192.168.0.183', os.name: 'Windows 7', os.arch:
 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
      at process._tickCallback (internal/process/next_tick.js:109:7)

  2) pcLogin : ie11 "before all" hook:
     Error: done() invoked with non-Error: The best matching driver provider org
.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance fo
r Capabilities [{ie.ensureCleanSession=true, hosts=, browserName=ie11, platform=
ANY}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'yzy-PC', ip: '192.168.0.183', os.name: 'Windows 7', os.arch:
 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: driver.version: unknown
      at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by yaniswang** [comment]
浏览器名称写错了，应该是：chrome, ie 11
不是：crome, ie11

**Comment by chyzhangxue** [comment]
好的，谢谢！

**Comment by chyzhangxue** [comment]
搞定了，感谢！
