### ISSUE TITLE
不能启动Chrome浏览器

### ISSUE THREAD

**Issue by noobwu** [alibaba/uirecorder#99]
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }
![image](https://cloud.githubusercontent.com/assets/4328356/26761637/e94d80d8-4965-11e7-9e9b-42ab8b6e1975.png)

**Comment by xudafeng** [comment]
chromedriver下载成功了吗

**Comment by yaniswang** [comment]
9766是chromedriver监听的端口号，看样子应该是chromedriver没有安装成功，或者启动失败
你重启下电脑，再试试看，如果还是出现这个问题，那可能就是chromedriver没有安装成功。

你是用cnpm命令安装的吗？

**Comment by yaniswang** [comment]
用cnpm安装后，问题修复，这个问题关闭了

**Comment by noobwu** [comment]
用cnpm安装成功不过用mocha启动chrome失败

chromedriver启动成功，chromedriver错误信息如下：
![qq 20170605162304](https://cloud.githubusercontent.com/assets/4328356/26776519/09152fa0-4a0c-11e7-8f41-e6f63b9ab0ae.png)
[](url)

Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:91)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:637)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:694)
        at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.maximize(RemoteWebDriver.java:925)
        at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWindow.maximize(EventFiringWebDriver.java:641)
        at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:30)
        at org.openqa.selenium.remote.server.handler.MaximizeWindow.call(MaximizeWindow.java:22)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:139)
        at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:87)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:161)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
        ... 11 
mocha 错误信息如下


1) sample/test.spec : chrome "before all" hook:
     Error: the string "java.net.SocketException: Connection reset\nBuild info: version: '3.4.0', revision: 'unknown', time: 'unknown'\nSystem info: host: '
![qq 20170605162304](https://cloud.githubusercontent.com/assets/4328356/26776495/f47dbc2e-4a0b-11e7-8077-c36cb18ee072.png)
![qq 20170605162337](https://cloud.githubusercontent.com/assets/4328356/26776497/f4bb5bd8-4a0b-11e7-9e69-f546ab1f6863.png)

', ip: '169.254.75.202', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'\nDriver info: driver.version: RemoteWebDriver" was thrown, throw an Error :)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)
c
![qq 20170605162304](https://cloud.githubusercontent.com/assets/4328356/26776411/9f6d6c84-4a0b-11e7-927d-51dabfc84d70.png)
![qq 20170605162337](https://cloud.githubusercontent.com/assets/4328356/26776417/a5ea1a08-4a0b-11e7-9cfb-e83f5271a96b.png)


Chrome启动到data:就不动了

**Comment by yaniswang** [comment]
你的selenium是用什么方式启动的？

是用npm run server启动的吗？

**Comment by noobwu** [comment]
我用
java -jar -Dwebdriver.chrome.driver="chromedriver_win32\chromedriver.exe" selenium-server-standalone-3.4.0.jar
非常感谢，终于跑起来了
